# Glass spheres scene - demonstrates transparency and refraction
[scene]
name = "Glass Spheres"
description = "Transparent and reflective spheres demonstrating advanced materials"
version = "1.0"

[scene.render]
width = 800
height = 600
samples = 1
max_bounces = 8  # Higher bounces for glass
background = [0.1, 0.1, 0.2]

[camera]
position = [0.0, 2.0, -8.0]
look_at = [0.0, 1.0, 0.0]
up = [0.0, 1.0, 0.0]
field_of_view = 0.785  # π/4 radians

[[lights]]
type = "point"
position = [-5.0, 10.0, -5.0]
intensity = [1.0, 1.0, 1.0]

[[lights]]
type = "point"
position = [5.0, 10.0, -5.0]
intensity = [0.5, 0.5, 0.8]

# Material definitions
[materials.glass]
color = [1.0, 1.0, 1.0]
ambient = 0.0
diffuse = 0.1
specular = 0.9
shininess = 300.0
reflective = 0.9
transparency = 0.9
refractive_index = 1.5

[materials.mirror]
color = [0.1, 0.1, 0.1]
ambient = 0.0
diffuse = 0.1
specular = 0.9
shininess = 200.0
reflective = 0.9
transparency = 0.0
refractive_index = 1.0

[materials.marble_floor]
color = [0.8, 0.8, 0.8]
ambient = 0.1
diffuse = 0.8
specular = 0.2
shininess = 50.0
reflective = 0.1
transparency = 0.0
refractive_index = 1.0

[patterns.marble]
type = "rings"
colors = [
  [0.9, 0.9, 0.9],  # Light gray
  [0.7, 0.7, 0.7],  # Medium gray
  [0.5, 0.5, 0.5]   # Dark gray
]

# Floor
[[objects]]
type = "plane"
[objects.material]
color = [0.8, 0.8, 0.8]
ambient = 0.1
diffuse = 0.8
specular = 0.2
shininess = 50.0
reflective = 0.1
pattern = "marble"

# Glass sphere - large
[[objects]]
type = "sphere"
material = "glass"
[objects.transform]
translation = [0.0, 1.0, 0.0]

# Glass sphere - small
[[objects]]
type = "sphere"
material = "glass"
[objects.transform]
translation = [2.5, 0.5, 1.0]
scale = [0.5, 0.5, 0.5]

# Mirror sphere
[[objects]]
type = "sphere"
material = "mirror"
[objects.transform]
translation = [-2.0, 1.5, 2.0]
scale = [1.5, 1.5, 1.5]

# Glass cube
[[objects]]
type = "cube"
material = "glass"
[objects.transform]
translation = [3.0, 1.0, -1.0]
rotation = [0.0, 0.785, 0.0]  # π/4 radians